// Automated accessibility audit for the Nocturne prototype (axe-core).
// Runs axe against EVERY state in the designed dark theme at 390px, both
// worlds for the shared states, plus 200%-text spot checks, and writes
// reports/a11y-report.md.
//
// Usage (from design-nocturne/app/): npm run a11y

import { chromium } from 'playwright';
import { spawn } from 'node:child_process';
import { existsSync } from 'node:fs';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const ROOT = new URL('..', import.meta.url).pathname;
const PORT = 4183;
const BASE = `http://localhost:${PORT}/`;

const STATES = [
  'first-launch', 'today', 'how', 'easier',
  'active', 'paused', 'complete', 'question', 'acknowledge',
  'journey', 'week-transition', 'week-12',
  'missed-one', 'missed-several', 'long-absence', 'programme-pause',
  'settings', 'subscription', 'expired', 'restore',
];
const BOTH = new Set([
  'first-launch', 'today', 'how', 'journey', 'long-absence',
  'week-12', 'subscription', 'settings', 'active', 'complete',
]);
const SCALE_SPOT = new Set(['today', 'journey', 'how', 'long-absence', 'subscription', 'settings']);

function url(world, state, scale = '100') {
  const q = new URLSearchParams({ vp: '390', motion: 'full', scale });
  return `${BASE}#/${world}/${state}?${q}`;
}

async function main() {
  const server = spawn('node', [join(ROOT, 'tools/serve.mjs'), String(PORT)], { stdio: 'ignore' });
  await new Promise((r) => setTimeout(r, 600));
  const axeSource = await readFile(require.resolve('axe-core/axe.min.js'), 'utf8');

  const exe = process.env.LAB_CHROMIUM || '/opt/pw-browsers/chromium-1194/chrome-linux/chrome';
  const browser = await chromium.launch(existsSync(exe) ? { executablePath: exe } : {});

  const results = [];
  let checks = 0;

  try {
    const page = await browser.newPage({ viewport: { width: 390, height: 844 } });

    for (const state of STATES) {
      const runs = [{ scale: '100', worlds: BOTH.has(state) ? ['strength', 'writing'] : ['strength'] }];
      if (SCALE_SPOT.has(state)) runs.push({ scale: '200', worlds: ['strength'] });
      for (const run of runs) {
        for (const wld of run.worlds) {
          await page.goto(url(wld, state, run.scale));
          await page.waitForTimeout(state === 'week-transition' ? 1600 : 900);
          await page.evaluate(axeSource);
          const res = await page.evaluate(async () =>
            window.axe.run(document.body, {
              runOnly: { type: 'tag', values: ['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa'] },
            })
          );
          checks++;
          for (const v of res.violations) {
            results.push({
              state, world: wld, mode: `dark/${run.scale}%`,
              id: v.id, impact: v.impact, help: v.help,
              nodes: v.nodes.slice(0, 3).map((n) => n.target.join(' ')).join(' · '),
            });
          }
        }
      }
    }
  } finally {
    await browser.close();
    server.kill();
  }

  const bySeverity = {};
  results.forEach((r) => (bySeverity[r.impact] = (bySeverity[r.impact] || 0) + 1));

  let md = `# Automated accessibility audit — Nocturne prototype (axe-core)\n\n`;
  md += `Generated by \`npm run a11y\` against the built app. Scope: WCAG 2.x A/AA rule tags, `;
  md += `every state in the designed dark theme at 390px (both worlds for the shared states), `;
  md += `200% text spot-checks on ${[...SCALE_SPOT].join(', ')}.\n\n`;
  md += `**${checks} state-audits run · ${results.length} violations found**`;
  md += ` (critical: ${bySeverity.critical || 0}, serious: ${bySeverity.serious || 0}, moderate: ${bySeverity.moderate || 0}, minor: ${bySeverity.minor || 0})\n\n`;
  if (results.length) {
    md += `| State | World | Mode | Rule | Impact | Where |\n|---|---|---|---|---|---|\n`;
    for (const r of results) {
      md += `| ${r.state} | ${r.world} | ${r.mode} | ${r.id} — ${r.help} | ${r.impact} | \`${r.nodes}\` |\n`;
    }
  } else {
    md += `No violations at the audited rule set. (Automated checks are necessary, not sufficient — manual review recorded separately.)\n`;
  }
  await mkdir(join(ROOT, 'reports'), { recursive: true });
  await writeFile(join(ROOT, 'reports', 'a11y-report.md'), md);
  console.log(md.split('\n').slice(0, 8).join('\n'));
  console.log(`\nreports/a11y-report.md written (${results.length} violations across ${checks} audits).`);
}

main().catch((e) => { console.error(e); process.exit(1); });
