// Automated accessibility audit for the design lab.
// Runs axe-core against every direction × state (both themes for key states,
// plus a 200%-text pass on Today/journey/how) inside the chromeless stage,
// and writes reports/a11y-report.md.
//
// Usage (from design-lab/): npm run a11y   [-- --dir a]

import { chromium } from 'playwright';
import { spawn } from 'node:child_process';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const ROOT = new URL('..', import.meta.url).pathname;
const PORT = 4311;
const BASE = `http://localhost:${PORT}/app/index.html`;

const args = process.argv.slice(2);
const onlyDir = args.includes('--dir') ? args[args.indexOf('--dir') + 1] : null;

const STATES = [
  'first-launch', 'explanation', 'explore', 'suitability', 'start-journey',
  'today', 'why', 'how', 'prep', 'easier', 'advanced',
  'begin', 'active', 'paused', 'complete', 'question', 'acknowledge',
  'journey', 'week-transition', 'missed-one', 'missed-several', 'long-absence',
  'programme-pause', 'offline', 'loading', 'error', 'empty',
  'week-12', 'artefact', 'handover', 'subscription', 'expired', 'restore', 'specimen',
];
const DARK_SPOT = new Set(['today', 'journey', 'active', 'subscription', 'long-absence', 'week-12']);
const SCALE_SPOT = new Set(['today', 'journey', 'how', 'long-absence']);

function url(dir, world, state, { theme = 'light', scale = '100' } = {}) {
  const q = new URLSearchParams({ chrome: 'off', theme, scale, motion: 'full', vp: 'standard' });
  return `${BASE}#/${dir}/${world}/${state}?${q}`;
}

async function main() {
  const server = spawn('node', [join(ROOT, 'tools/serve.mjs'), String(PORT)], { stdio: 'ignore' });
  await new Promise((r) => setTimeout(r, 700));
  const axeSource = await readFile(require.resolve('axe-core/axe.min.js'), 'utf8');

  const exe = process.env.LAB_CHROMIUM || '/opt/pw-browsers/chromium-1194/chrome-linux/chrome';
  const browser = await chromium.launch(
    (await import('node:fs')).existsSync(exe) ? { executablePath: exe } : {}
  );

  const dirs = onlyDir ? [onlyDir] : ['a', 'b', 'c'];
  const results = [];
  let checks = 0;

  try {
    const page = await browser.newPage({ viewport: { width: 430, height: 820 } });
    await page.goto(url(dirs[0], 'strength', 'today'));
    await page.evaluate(axeSource);

    for (const dir of dirs) {
      for (const state of STATES) {
        const runs = [{ theme: 'light', scale: '100' }];
        if (DARK_SPOT.has(state)) runs.push({ theme: 'dark', scale: '100' });
        if (SCALE_SPOT.has(state)) runs.push({ theme: 'light', scale: '200' });
        for (const mode of runs) {
          // strength world everywhere; writing world additionally on the default Today pass
          const worlds = state === 'today' && mode.scale === '100' && mode.theme === 'light'
            ? ['strength', 'writing']
            : ['strength'];
          for (const wld of worlds) {
            await page.goto(url(dir, wld, state, mode));
            await page.evaluate(axeSource);
            await page.waitForTimeout(220);
            const res = await page.evaluate(async () => {
              return await window.axe.run(document.querySelector('.stage'), {
                runOnly: { type: 'tag', values: ['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa'] },
              });
            });
            checks++;
            for (const v of res.violations) {
              results.push({
                dir, state, world: wld, mode: `${mode.theme}/${mode.scale}%`,
                id: v.id, impact: v.impact, help: v.help,
                nodes: v.nodes.slice(0, 3).map((n) => n.target.join(' ')).join(' · '),
              });
            }
          }
        }
      }
    }
  } finally {
    await browser.close();
    server.kill();
  }

  const bySeverity = { critical: 0, serious: 0, moderate: 0, minor: 0 };
  results.forEach((r) => bySeverity[r.impact] = (bySeverity[r.impact] || 0) + 1);

  let md = `# Automated accessibility audit (axe-core)\n\n`;
  md += `Generated by \`npm run a11y\` from the executable lab. Scope: WCAG 2.x A/AA rule tags, every state in ${dirs.length} direction(s) (light), dark spot-checks on ${[...DARK_SPOT].join(', ')}, 200% text spot-checks on ${[...SCALE_SPOT].join(', ')}.\n\n`;
  md += `**${checks} state-audits run · ${results.length} violations found** (critical: ${bySeverity.critical || 0}, serious: ${bySeverity.serious || 0}, moderate: ${bySeverity.moderate || 0}, minor: ${bySeverity.minor || 0})\n\n`;
  if (results.length) {
    md += `| Direction | State | World | Mode | Rule | Impact | Where |\n|---|---|---|---|---|---|---|\n`;
    for (const r of results) {
      md += `| ${r.dir} | ${r.state} | ${r.world} | ${r.mode} | ${r.id} — ${r.help} | ${r.impact} | \`${r.nodes}\` |\n`;
    }
  } else {
    md += `No violations at the audited rule set. (Automated checks are necessary, not sufficient — see docs/03-ux/design-accessibility-review.md for the manual review.)\n`;
  }
  await mkdir(join(ROOT, 'reports'), { recursive: true });
  await writeFile(join(ROOT, 'reports', 'a11y-report.md'), md);
  console.log(md.split('\n').slice(0, 8).join('\n'));
  console.log(`\nreports/a11y-report.md written (${results.length} violations across ${checks} audits).`);
}

main().catch((e) => { console.error(e); process.exit(1); });
