// Automated accessibility audit for the refined Atelier prototype.
// Runs axe-core against every state (light), dark spot-checks, and a
// 200%-text pass on key states, and writes reports/a11y-report.md.
//
// Usage (from design-refinement/): npm run a11y

import { chromium } from 'playwright';
import { spawn } from 'node:child_process';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { createRequire } from 'node:module';
import { STATES } from '../app/states.js';

const require = createRequire(import.meta.url);
const ROOT = new URL('..', import.meta.url).pathname;
const PORT = 4175;
const BASE = `http://localhost:${PORT}/app/index.html`;

const DARK_SPOT = new Set(['today', 'journey', 'active', 'subscription', 'long-absence', 'week-12', 'settings', 'first-launch']);
const SCALE_SPOT = new Set(['today', 'journey', 'how', 'long-absence', 'subscription', 'settings']);

function url(world, state, { theme = 'light', scale = '100' } = {}) {
  const q = new URLSearchParams({ theme, scale, motion: 'full', vp: 'standard' });
  return `${BASE}#/${world}/${state}?${q}`;
}

async function main() {
  const server = spawn('node', [join(ROOT, 'tools/serve.mjs'), String(PORT)], { stdio: 'ignore' });
  await new Promise((r) => setTimeout(r, 700));
  const axeSource = await readFile(require.resolve('axe-core/axe.min.js'), 'utf8');

  const exe = process.env.LAB_CHROMIUM || '/opt/pw-browsers/chromium-1194/chrome-linux/chrome';
  const browser = await chromium.launch(
    (await import('node:fs')).existsSync(exe) ? { executablePath: exe } : {}
  );

  const results = [];
  let checks = 0;

  try {
    const page = await browser.newPage({ viewport: { width: 430, height: 820 } });

    for (const state of STATES) {
      const runs = [{ theme: 'light', scale: '100' }];
      if (DARK_SPOT.has(state)) runs.push({ theme: 'dark', scale: '100' });
      if (SCALE_SPOT.has(state)) runs.push({ theme: 'light', scale: '200' });
      for (const mode of runs) {
        const worlds = state === 'today' && mode.scale === '100' && mode.theme === 'light'
          ? ['strength', 'writing']
          : ['strength'];
        for (const wld of worlds) {
          await page.goto(url(wld, state, mode));
          await page.evaluate(axeSource);
          await page.waitForTimeout(220);
          const res = await page.evaluate(async () => {
            return await window.axe.run(document.querySelector('.stage'), {
              runOnly: { type: 'tag', values: ['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa'] },
            });
          });
          checks++;
          for (const v of res.violations) {
            results.push({
              state, world: wld, mode: `${mode.theme}/${mode.scale}%`,
              id: v.id, impact: v.impact, help: v.help,
              nodes: v.nodes.slice(0, 3).map((n) => n.target.join(' ')).join(' · '),
            });
          }
        }
      }
    }
  } finally {
    await browser.close();
    server.kill();
  }

  const bySeverity = { critical: 0, serious: 0, moderate: 0, minor: 0 };
  results.forEach((r) => bySeverity[r.impact] = (bySeverity[r.impact] || 0) + 1);

  let md = `# Automated accessibility audit — refined Atelier prototype (axe-core)\n\n`;
  md += `Generated by \`npm run a11y\`. Scope: WCAG 2.x A/AA rule tags, every state (light), dark spot-checks on ${[...DARK_SPOT].join(', ')}, 200% text spot-checks on ${[...SCALE_SPOT].join(', ')}.\n\n`;
  md += `**${checks} state-audits run · ${results.length} violations found** (critical: ${bySeverity.critical || 0}, serious: ${bySeverity.serious || 0}, moderate: ${bySeverity.moderate || 0}, minor: ${bySeverity.minor || 0})\n\n`;
  if (results.length) {
    md += `| State | World | Mode | Rule | Impact | Where |\n|---|---|---|---|---|---|\n`;
    for (const r of results) {
      md += `| ${r.state} | ${r.world} | ${r.mode} | ${r.id} — ${r.help} | ${r.impact} | \`${r.nodes}\` |\n`;
    }
  } else {
    md += `No violations at the audited rule set. (Automated checks are necessary, not sufficient — manual review recorded separately.)\n`;
  }
  await mkdir(join(ROOT, 'reports'), { recursive: true });
  await writeFile(join(ROOT, 'reports', 'a11y-report.md'), md);
  console.log(md.split('\n').slice(0, 8).join('\n'));
  console.log(`\nreports/a11y-report.md written (${results.length} violations across ${checks} audits).`);
}

main().catch((e) => { console.error(e); process.exit(1); });
